# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	config.vm.define 'Task1' do |node|
		node.vm.box = "ubuntu/bionic64" 
		node.vm.hostname = "task1"
		node.vm.network "public_network"
		node.vm.provider "virtualbox" do |vb|
			vb.name = "Task1"
			vb.memory = 1024
			vb.cpus = 2
		end
	end
end
